In [15]:
#Write a Python Program to Add Two Matrices?

import numpy as np               #importing numpy libraries in python
a=np.array([[1,0],[0,1]])
b=np.array([[3,4],[4,3]])
c=a+b
print('Added matrix=\n',c)

Added matrix=
 [[4 4]
 [4 4]]


In [14]:
#Write a Python Program to Multiply Two Matrices?
import numpy as np
a=np.array([[2,0],[0,2]])
b=np.array([[3,4],[4,3]])
c=np.dot(a,b)
print('Multiplied matrix=\n',c)

Multiplied matrix=
 [[6 8]
 [8 6]]


In [16]:
#Write a Python Program to Transpose a Matrix?
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.transpose(a)
print('Initial Matrix=\n',a,'\nTransposed Matrix B=\n',b)

Initial Matrix=
 [[1 2]
 [3 4]] 
Transposed Matrix B=
 [[1 3]
 [2 4]]


In [26]:
#Write a Python Program to Sort Words in Alphabetic Order?

a=input('Enter a sentence=')
a=a.lower().split()
a.sort()
for i in a:
    print(i)


Enter a sentence=Happy Diwali to all
all
diwali
happy
to


In [4]:
#Write a Python Program to Remove Punctuation From a String?

a=input('Enter a sentence=\n')
n=a.replace('.','')

print('\n\n',n,sep='')


Enter a sentence=
Python is a high-level, general-purpose and a very popular programming language. Python programming language (latest Python 3) is being used in web development, Machine Learning applications, along with all cutting edge technology in Software Industry. Python Programming Language is very well suited for Beginners, also for experienced programmers with other programming languages like C++ and Java.


Python is a high-level, general-purpose and a very popular programming language Python programming language (latest Python 3) is being used in web development, Machine Learning applications, along with all cutting edge technology in Software Industry Python Programming Language is very well suited for Beginners, also for experienced programmers with other programming languages like C++ and Java
